/* macros.js — Async loader for the file-based prebuilt library + drawer wiring */

const Macros = (() => {

  const CATEGORIES = [];
  let SHARED_LIB = '';

  // Load prebuilts from the bundled registry (window.LUIGI_PREBUILTS).
  // The bundle is generated by tools/build-prebuilts.py from the .logo
  // files and committed to git, so this works equally on file:// and
  // http:// — no fetch required.
  function loadPrebuilts() {
    const reg = window.LUIGI_PREBUILTS;
    if (!reg) {
      throw new Error('prebuilts/registry.js not loaded — run tools/build-prebuilts.py');
    }
    SHARED_LIB = reg.sharedLib || '';
    for (const cat of reg.categories) {
      CATEGORIES.push({
        id: cat.id,
        label: cat.label,
        macros: cat.prebuilts.map(p => ({
          id: p.id, icon: p.icon, label: p.label, code: p.code,
        })),
      });
    }
  }

  // ── Drawer interaction state ──────────────────────────────────────
  let selectedMacro = null;
  let activeCat = 'shapes';

  function setSelected(macro, btn) {
    selectedMacro = macro;
    document.querySelectorAll('.macro-btn.selected').forEach(b => b.classList.remove('selected'));
    if (btn) btn.classList.add('selected');
    document.getElementById('macro-preview-code').textContent = macro.code;
    document.getElementById('macro-insert-btn').disabled = false;
    const runBtn = document.getElementById('macro-insert-run-btn');
    if (runBtn) runBtn.disabled = false;
  }

  function renderMacroGrid(catId) {
    const grid = document.getElementById('macro-grid');
    grid.innerHTML = '';
    const cat = CATEGORIES.find(c => c.id === catId);
    if (!cat) return;

    cat.macros.forEach(macro => {
      const btn = document.createElement('button');
      btn.className = 'macro-btn';
      btn.innerHTML = `<span class="icon">${macro.icon}</span><span class="label">${macro.label}</span>`;
      btn.title = `Preview ${macro.label}`;
      btn.addEventListener('click', () => setSelected(macro, btn));
      grid.appendChild(btn);
    });

    if (cat.macros.length > 0) {
      setSelected(cat.macros[0], grid.firstChild);
    }
  }

  function insertSelected() {
    if (!selectedMacro || !Editor.cm) return;
    Editor.cm.setValue(selectedMacro.code);
    Editor.cm.focus();
    Editor.cm.execCommand('goDocEnd');
    Drawer.close();
  }

  function insertAndRunSelected() {
    if (!selectedMacro || !Editor.cm) return;
    Editor.cm.setValue(selectedMacro.code);
    Drawer.close();
    // Run after the drawer close animation so the canvas is fully visible
    setTimeout(() => App.runProgram(selectedMacro.code), 50);
  }

  function init() {
    try {
      loadPrebuilts();
    } catch (e) {
      console.error('Failed to load prebuilts:', e);
      const grid = document.getElementById('macro-grid');
      if (grid) grid.innerHTML = `<div style="padding:16px;color:#f38ba8;">Failed to load pre-builts: ${e.message}</div>`;
      return;
    }

    document.querySelectorAll('.macro-tab').forEach(tab => {
      tab.addEventListener('click', () => {
        document.querySelectorAll('.macro-tab').forEach(t => t.classList.remove('active'));
        tab.classList.add('active');
        activeCat = tab.dataset.cat;
        renderMacroGrid(activeCat);
      });
    });

    document.getElementById('macro-insert-btn').addEventListener('click', insertSelected);
    document.getElementById('macro-insert-run-btn')?.addEventListener('click', insertAndRunSelected);

    renderMacroGrid(activeCat);
  }

  return {
    init,
    CATEGORIES,
    get SHARED_LIB() { return SHARED_LIB; },
  };
})();

/* ─── Drawer module ─────────────────────────────────────────────────── */
const Drawer = (() => {

  let currentPanel = null;

  function open(panel) {
    currentPanel = panel;
    document.getElementById('drawer-title').textContent =
      panel === 'macros' ? 'Pre-built Programs' : 'Command Reference';
    document.getElementById('drawer-macros').hidden = panel !== 'macros';
    document.getElementById('drawer-help').hidden   = panel !== 'help';
    document.getElementById('drawer').classList.add('open');
    document.getElementById('drawer-backdrop').classList.add('open');

    document.getElementById('btn-macros').classList.toggle('active', panel === 'macros');
    document.getElementById('btn-help').classList.toggle('active', panel === 'help');
  }

  function close() {
    currentPanel = null;
    document.getElementById('drawer').classList.remove('open');
    document.getElementById('drawer-backdrop').classList.remove('open');
    document.getElementById('btn-macros').classList.remove('active');
    document.getElementById('btn-help').classList.remove('active');
  }

  function toggle(panel) {
    if (currentPanel === panel) close();
    else open(panel);
  }

  function init() {
    document.getElementById('btn-macros').addEventListener('click', () => toggle('macros'));
    document.getElementById('btn-help').addEventListener('click', () => toggle('help'));
    document.getElementById('drawer-close').addEventListener('click', close);
    document.getElementById('drawer-backdrop').addEventListener('click', close);
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && currentPanel) close();
    });
  }

  return { init, open, close, toggle };
})();

window.addEventListener('DOMContentLoaded', () => {
  Macros.init();   // async — drawer renders when ready
  Drawer.init();
});
