#!/usr/bin/env python3
"""Build prebuilts/registry.js from .logo files + manifest.

Run after adding / editing any .logo file or index.json:

    python3 tools/build-prebuilts.py

Produces prebuilts/registry.js — a single browser-loadable bundle that
sets window.LUIGI_PREBUILTS = { sharedLib, categories }. The bundle is
checked into git so the app works on file:// without a local server.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREBUILTS = os.path.join(ROOT, 'prebuilts')
MANIFEST = os.path.join(PREBUILTS, 'index.json')
LIB_FILE = os.path.join(PREBUILTS, '_lib.logo')
OUT_FILE = os.path.join(PREBUILTS, 'registry.js')


def read(path: str) -> str:
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


def main() -> int:
    if not os.path.isfile(MANIFEST):
        print(f"manifest not found: {MANIFEST}", file=sys.stderr)
        return 1
    if not os.path.isfile(LIB_FILE):
        print(f"_lib.logo not found: {LIB_FILE}", file=sys.stderr)
        return 1

    manifest = json.loads(read(MANIFEST))
    shared_lib = read(LIB_FILE)

    categories = []
    total = 0
    for cat in manifest['categories']:
        prebuilts = []
        for p in cat['prebuilts']:
            logo_path = os.path.join(PREBUILTS, p['file'])
            if not os.path.isfile(logo_path):
                print(f"missing: {p['file']}", file=sys.stderr)
                return 1
            prebuilts.append({
                'id': p['id'],
                'label': p['label'],
                'icon': p['icon'],
                'code': read(logo_path),
            })
            total += 1
        categories.append({
            'id': cat['id'],
            'label': cat['label'],
            'prebuilts': prebuilts,
        })

    bundle = {
        'sharedLib': shared_lib,
        'categories': categories,
    }

    header = (
        '/* AUTO-GENERATED by tools/build-prebuilts.py — do not edit by hand.\n'
        ' * Edit the .logo files under prebuilts/<category>/ and rerun the\n'
        ' * build script. The .logo files are the source of truth.\n'
        ' */\n'
    )
    body = 'window.LUIGI_PREBUILTS = ' + json.dumps(bundle, ensure_ascii=False, indent=2) + ';\n'

    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write(body)

    print(f"Wrote {OUT_FILE}")
    print(f"  {len(categories)} categories, {total} prebuilts, lib {len(shared_lib)} chars")
    return 0


if __name__ == '__main__':
    sys.exit(main())
